[platform]
type = "KINCONY_SERVER_MINI"
host = "central.local"
log_events = true  # Optional
[[platform.mqtt]]
broker = "local"
topic = "ksm/switches"
[[platform.switch]]
digital_input = 1
device_id = "desk_switch"
bounce_time = 0.05  # Optional - in seconds
relays = [1]  # Optional - wired to relay 1
[[platform.relay]]
relay_channel = 1
device_id = "desk_lights"