# This an example sensor configuration file

[[sensor]]
# mandatory fields
type = "sen0395"  # https://wiki.dfrobot.com/mmWave_Radar_Human_Presence_Detection_SKU_SEN0395
name = "desk"
port = "serial:///dev/ttyAMA0"
# optional fields
enabled = true  # Automatically start reading the sensor upon startup (MQTT, presence print, etc.)
autostart = true  # Automatically start the sensor scanning upon startup (unless already started)
print_presence = true  # Print presence changes to stdout
[[sensor.mqtt]]
broker = "local-rpi"
topic = "living_room/desk/presence"
[[sensor.ws]]
endpoint = "local-rpi"

[[sensor]]
type = "sen0311"
name = "shower"
port = "serial:///dev/ttyAMA3"
enabled = true
[sensor.presence]
# Presence is detected when the measurement is between 100 and 1000 cm
threshold_presence = 100
threshold_absence = 1000
# optional fields
hysteresis_count = 2  # 2 consecutive measurements are required to change the presence state
delay_presence = 0  # No delay - same as this field would be omitted
delay_absence = 3.5  # The presence value is changed to `absence` after 3.5 seconds of continuos absence state
print_presence = true
[[sensor.presence.ws]]
endpoint = "rpi_main
